### ISSUE TITLE
cmwc.random64 bug when used with (min, max)

### ISSUE THREAD

**Issue by nhartland** [iskolbin/lcmwc#1]
First of all, thanks for making this available.

I spotted a small bug in cmwc.random64 at https://github.com/iskolbin/lcmwc/blob/d536f3989120c0631392d50da0cc745bd1ad85cd/cmwc.lua#L113

Where you reference a previously undefined `q` (I guess you meant `a`?)

Just to confirm the behaviour (I'm admittedly not on that great footing with prngs) 
is cmwc.random64 supposed to return a float between [min, max] and cmwc.random32 should return an int?

**Comment by iskolbin** [comment]
Hi, thx for the report!
I obviously mistyped, but the code was not that good anyway:) rewritten and added unit tests.
About API: library has `rand`, `random32` and `random64`. 
`rand` returns raw uint32, and `random32` and `random64` trying to somehow mimic `math.random`. The point is stock Lua uses doubles which is 53-bit precision, obviously you cannot achieve  such precision with only 32-bits, so if you need high quality random number, you need to take 2 32-bit numbers and combine them.

**Comment by nhartland** [comment]
Perfect, thanks!
